### ISSUE TITLE
can't  login on iOS13

### ISSUE THREAD

**Issue by yingkai-liao** [sassembla/toriki#2]
On iOS 13 , the parameter ```sourceApplication``` has been removed from ```onOpenURL```.

```
- (void)onOpenURL:(NSNotification *)notification
{
    [[TKTwitter sharedInstance]
     onAppLaunch:notification.userInfo[@"url"]
     sourceApplication:notification.userInfo[@"sourceApplication"]];
}
```
```
- (void)onAppLaunch:(NSURL *)url sourceApplication:(NSString *)sourceApplication
{
	BOOL isSSOBundle = [sourceApplication hasPrefix:@"com.twitter"] || [sourceApplication hasPrefix:@"com.atebits"];
```
the value of ```sourceApplication``` pass to ```onAppLaunch``` is nil, so that the variable ```isSSOBundle```  is always false, and unity can't get any callback after ```applicationDidBecomeActive```.

---

for now, I changed the condition of ```isSSOBundle``` , and it works
```
	NSString *urlString = url.absoluteString;
	BOOL isSSOBundle = [urlString hasPrefix:@"twitterkit"];
```

**Comment by sassembla** [comment]
thank you for information! I'll fix it.

**Comment by sassembla** [comment]
just fixed issue. 964b711f9a7679a43b6b160746df965038808e18
