### ISSUE TITLE
User rejected 

### ISSUE THREAD

**Issue by SupranJowti** [sassembla/toriki#3]
User rejected error even if you're trying to reenter

**Comment by sassembla** [comment]
thank you for issue, may I ask you to describe about more specific situation?

# abstract of this issue
- Unity version
- The Platform information you encountered this issue e,g, iOS 14.5 
- The Device you encountered this issue e,g, iPhone12

# how to reproduct issue

**Comment by SupranJowti** [comment]
I think the problem arises if you cancel it for the first time.

Unity version:　2019.4.13f1
The Platform information: Android 8
The Device you encountered this issue: Xiaomi Redmi note series

**Comment by SupranJowti** [comment]
@sassembla thank you for your reply. do you have any solution?

**Comment by sassembla** [comment]
Sorry for late @SupranJowti , 
Unfortunately I don't have any Android 8 device now. and my Android devices(OS10 or later~) could not repro this issue.


I assume that the step of reproduce is below, is it correct?

1. start your Unity app on your Android OS8 device.
2. start Toriki Twitter Sign in process. this may open Twitter app.
3. then cancel it on Twitter app.
4. automatically back to your app.
5. then, retry step 2 makes some errors.


And so, I want to know what code are you using in your app. can you show me it?

**Comment by SupranJowti** [comment]
@sassembla  Thank you for your reply. 

The problem was occurring due to suspend my app on Twitter. Twitter automated system suspended my app. it tracks it as spam. You can reproduce the problem if you try multiple login.

I requested for twitter support but no reply so far. 
So that I created a new app. The problem resolved.

but it will happen again if any user tries to login multiple time.

**Comment by sassembla** [comment]
thank you for reply! maybe it is not Toriki's problem,,,
