### ISSUE TITLE
'RegisterMonoModules.h' file not found XCode iOS

### ISSUE THREAD

**Issue by yasunogithub** [sassembla/toriki#4]
same problem? https://github.com/facebook/facebook-sdk-for-unity/issues/323
Unity 2020.3.3f1

**Comment by yasunogithub** [comment]
may be helpful https://github.com/facebook/facebook-sdk-for-unity/issues/359#issuecomment-583557205

**Comment by sassembla** [comment]
thank you for reporting! we'll adopt it (or, of course PR welcome.)

**Comment by sassembla** [comment]
fixed in https://github.com/sassembla/toriki/releases/tag/0.9.3 . please let me know if still have some problems. thank you!
