### ISSUE TITLE
Access user id and email

### ISSUE THREAD

**Issue by IsmaeelGoraya** [sassembla/toriki#6]
@sassembla Thank you for doing this. Really helped me to update my old twitter kit based iOS build. Can we modify headers to access email and user id of twitter user through login?

**Comment by sassembla** [comment]
hi! sorry for late.

> Can we modify headers to access email and user id of twitter user through login?

What part of the code do you want to change, etc.? 
Please let us know if there are any specific areas.

**Comment by IsmaeelGoraya** [comment]
no worries, 

Sure, so currently we get nickname, accessToken and accessSecret on login and parse them in C#. I used twitter kit for android and we get name email and userid on auth response. So, I was thinking if we can modify our objective-c file for this requirement.

<img width="383" alt="Screenshot 2022-10-06 at 12 31 09 PM" src="https://user-images.githubusercontent.com/38508376/194245867-4eb36bbe-4eff-4317-8e99-c65782509d28.png">

<img width="704" alt="Screenshot 2022-10-06 at 12 30 26 PM" src="https://user-images.githubusercontent.com/38508376/194245886-bab60bcb-6756-46b6-8cb0-213d3bde639b.png">

**Comment by IsmaeelGoraya** [comment]
@sassembla Sorry, my bad. Didn't looked the login code in my other project carefully. Firebase was being used. As, far as twitter is concerned twitter response to auth API is token, secret and username. Closing this issue.
